### ISSUE TITLE
Running Serverless workload on Kubernetes

### ISSUE THREAD

**Issue by pmbanugo** [foobaragency/knowledge-friday#20]
### Abstract

Serverless is a way to describe the services and strategies that enable you to go from idea to production faster, with lower cost. Services like AWS Lambda allow you to run your code in response to events from different event sources, with autoscaling. 

One of the challenges with many serverless platforms is the lack of easy portability across vendor, or moving from on-premise to cloud. What if there's a way to deploy serverless applications that are portable, adapt at scale and event-driven.  

In this talk, I'll introduce you to Knative, a Kubernetes-based platform to deploy and manage modern serverless workloads. I'll do a demo on how to deploy an app/service, show you how the autoscaling works, and if there's time, show how to do Canary or Blue/Green Deployment.

### Good to know

Estimated duration: 20 - 30 minutes.
Pre-requisite: Basic knowledge of container/docker will be good to know but not required. 
Q/A: I'm open to question at the end of the talk. Should be time-boxed to a max of 10 minutes.

**Comment by ezesundayeze** [comment]
@pmbanugo this sounds interesting. is there a slide for this talk I can look at?

**Comment by pmbanugo** [comment]
@ezesundayeze  I'll see if I can find the slides and share them.

**Comment by ezesundayeze** [comment]
Thanks
