### ISSUE TITLE
Introduction to Apache Kafka and ksqlDB

### ISSUE THREAD

**Issue by l-Leniac-l** [foobaragency/knowledge-friday#27]
### Abstract

The power of microservices relies on flexibility. The idea of having multiple independent services and apps talking to each other to compose extensive systems sometimes gets limited by underlying infrastructure problems. Microservices start sharing resources like databases, caching tools, and so on. When you realize what you're calling microservices is nothing but a monolith built into different APIs.

But, what if you could build independent apps with independent resources and the ability to communicate with each other in a real-time fashion? That's the power of event streams. That's the power given to you by Apache Kafka.

Apache Kafka is THE go-to tool for real-time event streaming, and Kafka streams a powerful programmable interface. What if you could process events as simple as writing SQL commands? Well, that's the beauty of ksqlDB.

Let's rock 'em some events, shall we?

### Good to know

Estimated duration: 40 - 50 minutes.
Pre-requisite: Basic knowledge of queues/SQL will be good to know but not required.
Q/A: I'm open to questions at the end of the talk.

**Comment by code-shambles** [comment]
![kfS-2022-01-28](https://user-images.githubusercontent.com/12255735/149920731-a80d1acd-76e3-4902-9627-f97ab7d345fd.png)
