### ISSUE TITLE
Remix Run Mutations

### ISSUE THREAD

**Issue by seblondono** [foobaragency/knowledge-friday#29]
[Remix Run](https://remix.run/) is one of the most recent players in the React framework scene, although they prefer themselves be called a ["Web Framework"](https://twitter.com/kentcdodds/status/1491908315185508352?s=20&t=j0-EvjyOwXMPv6RPeNByrQ). In this talk, we will go over some of the reasons they are correct on this preference by learning their approach on performing data mutations.

We will look at the example app - [Remix Jokes](https://remix.run/docs/en/v1/tutorials/jokes) - provided in their documentation. We will learn how to fetch jokes (GET) and how to create jokes (POST) using their abstractions. This will also gives us a chance to look a bit into Optimistic UI and expected and unexpected error recovery handling with Remix.

I hope this sounds exiting to you, because believe me when I tell you, it actually is! Join me in discovering this new approach to delivering great, and blazing fast user experiences with Remix 🚀

**Comment by code-shambles** [comment]
![image](https://user-images.githubusercontent.com/12255735/158399304-0db2ab4d-e0ba-44e9-97a4-566cc9e486be.png)
